### ISSUE TITLE
How does a user deactivate a homepage message?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/dl-edit#10]
User logs in. User then clicks on "homepage drawer" and is presented with a list of the created homepage messages. The user finds the item that is checked and unchecks it.

Should there just be a "display no message" button at the top that deselects the message no matter where it is in the list to make it easy to do this part?

**Comment by webmasterkai** [comment]
Just uncheck the currently active item?

**Comment by bjornmeansbear** [comment]
that works
